# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Opendeps < Formula
  desc "OpenDeps allows you to express your application's external runtime dependencies. Using OpenDeps, you use a YAML file to clearly communicate what APIs your software component needs to run correctly."
  homepage "https://github.com/opendeps/specification"
  version "0.1.6"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/opendeps/cli/releases/download/v0.1.6/opendeps_0.1.6_macOS_x86_64.tar.gz"
      sha256 "732bc8fbdabe084f094eacd467d59ff254a693832c6a99515bd81ec136b87c26"
    end
    if Hardware::CPU.arm?
      url "https://github.com/opendeps/cli/releases/download/v0.1.6/opendeps_0.1.6_macOS_arm64.tar.gz"
      sha256 "65ad9bc5ef390056d188751341e8603e35a4648de6da3ee5bb09cf88a5e1f953"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/opendeps/cli/releases/download/v0.1.6/opendeps_0.1.6_Linux_x86_64.tar.gz"
      sha256 "39b2e56ec0fdc2d3bb8fc248b83845b368ec37bafef554144c97b89a835ea345"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/opendeps/cli/releases/download/v0.1.6/opendeps_0.1.6_Linux_armv6.tar.gz"
      sha256 "c020b1be0b2edb557ad0b22c2b70638a88417f2ec13e06fe2e8f12f3ff1010db"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/opendeps/cli/releases/download/v0.1.6/opendeps_0.1.6_Linux_arm64.tar.gz"
      sha256 "d06bb1181a6fee3777e56d744626ce1b1a2484b4c7cc0c22650c3866bb3dd7bd"
    end
  end

  def install
    bin.install "opendeps"
  end

  def caveats; <<~EOS
    Live mocks feature requires Docker to be installed.
  EOS
  end
end
